version: "3"
services:
  contact-center:
    image: ${CC_IMAGE:-cskefu/contact-center:develop}
    restart: always
    ports:
      - "${CC_WEB_PORT:-8035}:8035"
      - "${CC_SOCKET_PORT:-8036}:8036"
    volumes:
      - ./contact-center/data:/data
      - ./contact-center/logs:/logs
    environment:
      - "JAVA_OPTS=-Xmx${CC_JAVA_XMX:-12288m} -Xms${CC_JAVA_XMS:-2048m} -XX:PermSize=256m -XX:MaxPermSize=1024m -Djava.net.preferIPv4Stack=true --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true --illegal-access=warn"
      - SERVER_PORT=8035
      - SERVER_LOG_PATH=/logs
      - SERVER_LOG_LEVEL=${LOG_LEVEL:-WARN}
      - WEB_UPLOAD_PATH=/data
      - UK_IM_SERVER_PORT=8036
      - UK_IM_SERVER_HOST=localhost
      - UK_IM_SERVER_THREADS=10
      # 春松客服配置 HTTPs / HTTPs for CSKeFu
      # In detail
      #     1) https://chatopera.blog.csdn.net/article/details/105820829
      #     2) https://github.com/cskefu/cskefu/issues/414#issuecomment-1437767407
      # In short
      #     1) Setup Load Balancing / Reverse Proxy
      #     2) Modify CS_IM_SERVER_SSL_PORT
      #         set CS_IM_SERVER_SSL_PORT=443
      - CS_IM_SERVER_SSL_PORT=${CC_SOCKET_PORT:-8036}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${DB_PASSWD:-123456}
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - CSKEFU_MODULE_CALLOUT=false
      - CSKEFU_MODULE_CONTACTS=true
      - CSKEFU_MODULE_CHATBOT=true
      - CACHE_SETUP_STRATEGY=${CACHE_SETUP_STRATEGY:-create_by_force}
      - SKYPE_CHANNEL_CRM=${SKYPE_CHANNEL_CRM:-placeholder}
      - BOT_THRESHOLD_FAQ_BEST_REPLY=${BOT_THRESHOLD_FAQ_BEST_REPLY:-0.9}
      - BOT_THRESHOLD_FAQ_SUGG_REPLY=${BOT_THRESHOLD_FAQ_SUGG_REPLY:-0.1}
      - CSKEFU_SETTINGS_WEBIM_VISITOR_SEPARATE=true
      - LICENSE_STORE_PROVIDER=${LICENSE_STORE_PROVIDER:-https://store.chatopera.com}
      - TONGJI_BAIDU_SITEKEY=${TONGJI_BAIDU_SITEKEY:-placeholder}
      - EXTRAS_LOGIN_BANNER=${NOTICE_LOGIN_BANNER:-off}
      - EXTRAS_LOGIN_CHATBOX=${EXTRAS_LOGIN_CHATBOX:-off}
      - EXTRAS_AUTH_SUPER_ADMIN_PASS=${EXTRAS_AUTH_SUPER_ADMIN_PASS:-}
      - EXTRAS_LOG_REQUEST=${EXTRAS_LOG_REQUEST:-off}
    depends_on:
      - mysql
      - redis
      - activemq

  activemq:
    image: cskefu/activemq:5.14.3
    restart: always
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=${DB_PASSWD:-123456}
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_MIN_MEMORY=1024
      - ACTIVEMQ_MAX_MEMORY=4096
    volumes:
      - ./database/activemq/data:/data
      - ./database/activemq/logs:/var/log/activemq
    ports:
      - "${ACTIVEMQ_PORT1:-8051}:8161"
      - "${ACTIVEMQ_PORT2:-8052}:61616"
      - "${ACTIVEMQ_PORT3:-8053}:61613"

  mysql:
    image: cskefu/mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD:-123456}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${DB_PASSWD:-123456}
    ports:
      - "${MYSQL_PORT:-8037}:3306"
    volumes:
      - ./database/mysql/data:/var/lib/mysql
    command: --max_allowed_packet=32505856

  redis:
    image: cskefu/redis:5.0.5
    environment:
      - REDIS_PASSWORD=${DB_PASSWD:-123456}
    restart: always
    volumes:
      - ./database/redis/data:/data
    ports:
      - "${REDIS_PORT:-8041}:6379"